name = "ust-student-bot"
main = "src/student/index.ts"
compatibility_date = "2024-12-01"
compatibility_flags = ["nodejs_compat"]

# تفعيل workers.dev URL
workers_dev = true

# Public non-secret vars
[vars]
BOT_USERNAME = "usttesterbot"
ENVIRONMENT = "production"
WORKERS_SUBDOMAIN = "atow73768"

# Secret: BOT_TOKEN
# لتعيينه: echo "TOKEN" | npx wrangler secret put BOT_TOKEN --config wrangler.student.toml
